dist: bionic

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/0.29.1/bazel_0.29.1-linux-x86_64.deb
#  - sha256sum -c tools/bazel_0.29.1-linux-x86_64.deb.sha256
  - sudo dpkg -i bazel_0.29.1-linux-x86_64.deb

language: cpp
compiler: clang
script:
  - bazel test --noshow_progress //...
  